# Generated by Django 5.2.4 on 2025-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applianceprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="appliance_images/"
            ),
        ),
    ]
